# Generated by Django 2.1.1 on 2018-12-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=False, to='bot_app.UserDetails')),
            ],
        ),
    ]
