# Generated by Django 2.1.1 on 2018-12-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
