# Generated by Django 2.1.1 on 2018-12-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_auto_20181219_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
