# Generated by Django 2.1.1 on 2018-12-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_auto_20181219_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='u_Requests',
        ),
    ]
