# Generated by Django 2.1.1 on 2018-12-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_auto_20181219_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_Requests',
            new_name='Requests',
        ),
    ]
