# Generated by Django 2.1.1 on 2018-12-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_auto_20181219_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('opt1', models.CharField(max_length=200)),
                ('opt2', models.CharField(max_length=200)),
                ('opt3', models.CharField(max_length=200)),
                ('opt4', models.CharField(max_length=200)),
            ],
        ),
    ]
